[project]
name = "omnia_timeseries"
version = "1.3.13"
authors = [
	{ name = "Equinor Omnia Industrial IoT Team", email = "omniaindiot@equinor.com" }
]
description = "Official Python SDK for the Omnia Timeseries API"
readme = "README.md"
requires-python = ">=3.8,<4.0"

dependencies =[
"requests",
"azure-identity >=1.19.0",
"azure-core",
"opentelemetry-instrumentation-requests >=0.48b0,<1.0.0",
"opentelemetry-api >=1.27.0,<2.0.0",
"cryptography >=43.0.1",
"pyjwt >=2.9.0"
]

[tool.poetry.group.test.dependencies]
pytest = "*"
requests-mock = "*"

[tool.poetry.group.dev.dependencies]

[project.urls]
repository = "https://github.com/equinor/omnia-timeseries-python"

[build-system]
requires = ["poetry-core>=2.0,<3.0"]
build-backend = "poetry.core.masonry.api"
